#!/usr/bin/env python3
# Erzeugt face_designer_html.h und hand_designer_html.h aus web/<designer>.css, .html und .js: das Markup bleibt
# Text, CSS und Skript werden ohne Kommentarzeilen gzip-komprimiert (spart ~90 KB Flash). Die Uhr sendet die Bytes
# unveraendert, der Browser entpackt. ?v= in den Adressen wechselt mit dem Inhalt, so darf der Browser sie behalten.
# Nach jeder Aenderung in web/ aus dem Projektordner aufrufen:  python web/build_web.py
#
# Generates face_designer_html.h and hand_designer_html.h from web/<designer>.css, .html and .js: the markup stays
# text, CSS and script are gzip-compressed without comment lines (saves ~90 KB of flash). The clock sends the bytes
# unchanged, the browser unpacks them. ?v= in the addresses changes with the content, so the browser may keep them.
# Run from the project folder after every change in web/:  python web/build_web.py

import gzip
import hashlib
import os
import textwrap

BASE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(BASE)

DESIGNERS = (
    # Quelle, Ziel, Symbol-Praefix, Adresse, Rohstring-Kennung, Beschreibung DE / EN
    # source, target, symbol prefix, address, raw string tag, description DE / EN
    ("face_designer", "face_designer_html.h", "FACE_DESIGNER", "/facedesigner", "FDRAW",
     "Zifferblatt-Designer", "Clock face designer", "FD"),
    ("hand_designer", "hand_designer_html.h", "HAND_DESIGNER", "/handdesigner", "HDRAW",
     "Zeiger-Designer", "Hand designer", "HD"),
)


def read(name):
    with open(os.path.join(BASE, name), encoding="utf-8") as f:
        return f.read().replace("\r\n", "\n")


def minify(text):
    # Ganze Kommentarzeilen, Leerzeilen und Einrueckung weg - die Quellen haben keine mehrzeiligen Strings
    # Whole comment lines, blank lines and indentation removed - the sources have no multi-line strings
    out = []
    for line in text.split("\n"):
        s = line.strip()
        if s and not s.startswith("//"):
            out.append(s)
    return "\n".join(out) + "\n"


def gz(text):
    return gzip.compress(text.encode("utf-8"), compresslevel=9, mtime=0)


def c_array(name, data):
    rows = []
    for i in range(0, len(data), 20):
        rows.append("    " + ", ".join("0x%02x" % b for b in data[i:i + 20]) + ",")
    return "static const uint8_t %s[] PROGMEM = {\n%s\n};\n" % (name, "\n".join(rows))


def build(src, target, prefix, url, tag, de, en, cfg):
    css, markup, js = read(src + ".css"), read(src + ".html"), read(src + ".js")
    css_gz, js_gz = gz(minify(css)), gz(minify(js))
    version = hashlib.sha1(css_gz + js_gz).hexdigest()[:8]
    page = ('<link rel="stylesheet" href="%s.css?v=%s">\n%s<script src="%s.js?v=%s"></script>\n'
            % (url, version, markup, url, version))

    def comment(text):
        return textwrap.fill(text, width=110, initial_indent="    // ", subsequent_indent="    // ") + "\n"

    header = (
        "#pragma once\n"
        + comment("ERZEUGT von web/build_web.py aus web/%s.css, .html und .js - dort aendern, dann das Skript "
                  "ausfuehren. %s (Seite %s): Markup nach Seitenkopf und JS-Objekt %s, CSS und Skript gzip-komprimiert "
                  "unter %s.css und %s.js." % (src, de, url, cfg, url, url))
        + "\n"
        + comment("GENERATED by web/build_web.py from web/%s.css, .html and .js - edit there, then run the script. "
                  "%s (page %s): markup after the page header and the JS object %s, CSS and script gzip-compressed "
                  "at %s.css and %s.js." % (src, en, url, cfg, url, url))
        + "\n"
    )
    body = (
        header
        + 'static const char %s_HTML[] PROGMEM = R"%s(\n%s)%s";\n\n' % (prefix, tag, page, tag)
        + c_array(prefix + "_CSS_GZ", css_gz) + "\n"
        + c_array(prefix + "_JS_GZ", js_gz)
    )
    with open(os.path.join(ROOT, target), "w", encoding="utf-8", newline="\n") as f:
        f.write(body)
    raw = len(css) + len(js)
    print("%-22s CSS+JS %6d -> %6d Bytes gzip, Markup %5d, v=%s" % (target, raw, len(css_gz) + len(js_gz), len(page), version))


if __name__ == "__main__":
    for d in DESIGNERS:
        build(*d)
